- setup/modules.json
- src/GUARDRAIL 1 PROTECT ROOT  GLOBAL ADMINS ACCOUNT/Audit/Get-AzureADLicenseType.psm1
- src/GuardRails-Localization/GR-ComplianceChecks-Msgs.psd1
- src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
We have made an official switch from AAD to MS Entra ID naming convention
1. Updates AAD to MS Entra ID
N/A
> switch from AAD to MS Entra ID naming

- .github/workflows/sign-scripts-development.yml
Fix Scope for GITHUB TOKEN to allow releases
1. Fix Scope for GITHUB TOKEN to allow releases
N/A
> fix scope for GITHUB TOKEN

- .github/workflows/release-pipeline.yml
Fix Scope in release pipeline workflow to create new releases
1. Fix Scope in release pipeline workflow to create new releases
N/A
N/A
> Fix Release Pipeline Scope

- .github/workflows/release-pipeline.yml
Apply GITHUB TOKEN permission at job level
1. Apply GITHUB TOKEN permission at job level
N/A
N/A
> Give appropriate permission to create release job

- setup/tags.json
Creating release v.1.1.8
N/A
Creating release v.1.1.8
N/A
> Creating New Release v1.1.8

- .github/workflows/auto-update-modules.yml
This PR will add the  ability to create a PR with updated modules when when tag.json is updated.
1. This PR will add the  ability to create a PR with updated modules when when tag.json is updated.
N/A
> Add automation for update modules Pre Release

- .github/workflows/auto-update-modules.yml
Fix indentation error
1. Fix indentation error
N/A
> Fix indentation error

- .github/workflows/auto-update-modules.yml
1. Small Improvements for modules update 
N/A
> only commit ps modules and add git config

- .github/workflows/auto-update-modules.yml
- Minor improvements for pipeline pre release
N/A
N/A
> Minor improvemnts for pipeline pre release

- setup/tags.json
- Create Release v1.1.9
N/A
N/A
> Release v1.1.9

- src/GuardRails-Localization/GR-ComplianceChecks-Msgs.psd1
- src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
GR1 ItemName change both in English and French
> Item name change GR1 issue 38

- setup/tags.json
- Pre Release Step to update tag.json and trigger modules update.
1. Pre Release Step to update tag.json and trigger modules update.
N/A
N/A
> Pre Release v1.2.0

- setup/tags.json
> [UPDATE] - Creating Pre Release v1.2.1

- README.md
README file is updated to newer content.
This pull request includes the updated content in the README file and updated links to TBS GR policy v1.0 and gcxchange documents (Architecture, Installation Playbook, and Remediation Playbook)
> [Update] README file with updated documentation

- .github/workflows/sign-scripts-development.yml
This pull request updates cac deploy job configs to test environment
This pull request replaces the hardcoded config value with GH environment vars
> [Update] Replace configs with Env vars

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- SECURITY.md
- SUPPORT.md
This pull request updates the following to the newest and also adds FR content
- CONTRIBUTING.md
- LICENSE 
- SECURITY.md
- SUPPORT.md
- Code of Conduct 
N/A
N/A
N/A
> [Enhancement] Update document contents

- setup/tags.json
This is the pre-release step to update tag.json and trigger modules update.
Pre Release Step to update tag.json and trigger modules update.
N/A
N/A
> Pre-release v1.2.2

- setup/modules.json
This PR removes the not-required attestation file reference from module json file
Same
N/A
> [Code cleanup] Remove attestation reference

- setup/tags.json
This is the pre-release step of v1.2.3 to update tag.json and trigger modules update.
Pre Release step to update tag.json and trigger modules update.
N/A
N/A
> Pre-release v1.2.3

- .github/workflows/deploy_dev_env.yml
Update azure/login and azure/powershell to version 2.0
1. *Replace me*
2. *Replace me*
3. *Replace me*
1. *Replace me*
2. *Replace me*
> Update azure/login and azure/powershell to version 2.0

- .github/workflows/sign-scripts-development.yml
Updated azure/login and azure/powershell to version 2.0
1. *Replace me*
2. *Replace me*
3. *Replace me*
1. *Replace me*
2. *Replace me*
> Updated azure/login and azure/powershell -Test pipeline 

- .github/workflows/release-pipeline.yml
Updated azure/login to v2
1. *Replace me*
2. *Replace me*
3. *Replace me*
1. *Replace me*
2. *Replace me*
> Updated azure/login to v2 - Release pipeline

- setup/departmentList.csv
- src/GuardrailsSolutionAcceleratorSetup/modules/Confirm-GSAConfigurationParameters/Confirm-GSAConfigurationParameters.psm1
Updated the url to retrieve list from main branch
Updated the url to retrieve list from main branch for the time being.
(Update the URL with release tag later before another release)
None
> [Fix] Updated the url to retrieve list from main branch

- .github/workflows/deploy_dev_env.yml
- .github/workflows/sign-scripts-development.yml
- In deployment scenarios, especially when deploying to environments like Azure, concurrent deployments can sometimes lead to conflicts or inconsistent states. By controlling concurrency, we can ensure that deployments happen in a predictable and controlled manner.
- By preventing multiple simultaneous deployments, we reduce the risk of race conditions and other issues that can arise when multiple deployments interfere with each other.
In current specific context, this configuration ensures that deployments to the "Deploy-Azure-CAC-Dev" and "Deploy-Azure-CAC-Test" environment are managed carefully, preventing potential issues caused by overlapping deployments and ensuring that each deployment completes before the next one starts.
1. Concurrency settings in CI/CD pipeline to be used to …
> [Enhancement] Add pipeline concurrency handling for Dev and Test deployment

- setup/tags.json
This is the pre-release step for v2.0.0 
Updating tags.json as pre-release step
N/A
N/A
> Pre-release v2.0.0

- src/GuardRails-Localization/GR-ComplianceChecks-Msgs.psd1
- src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
This PR is to update GR2 V1 compliance messages
This PR is to update GR2 V1 compliance messages
N/A
Tested in tenant
> GR2 V1 compliance message update

- setup/tags.json
This is the pre-release step of v2.1.0
Pre-release step of updating tags.json and trigger modules update
N/A
N/A
> Pre-release v2.1.0

- .github/workflows/release-pipeline.yml
Remove signing of modules and only create release 
1. Remove signing of modules and only create release 
N/A
N/A
> [BugFix] - Fix release pipeline

- .github/workflows/release-pipeline.yml
Add compress archive and exclude release assets as well as git and github folders 
1. Add compress archive and exclude release assets as well as git and github folders 
N/A
N/A
> [BugFix] - Add compress archive for zipping release artifact

- .github/workflows/sign-scripts-development.yml
- setup/modules.json
- src/GuardRails-Localization/GR-ComplianceChecks-Msgs.psd1
- src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
GR8 V2 New control for Cloud Infrastructure Deployment Guide or Applicable Landing Zone Details
This PR adds new control for Cloud Infrastructure Deployment Guide or Applicable Landing Zone Details (GR8V2) 
N/A
> [New control ] GR8 V2 Cloud Infrastructure Deployment Guide or Applicable Landing Zone Details

- setup/modules.json
- src/GuardRails-Localization/GR-ComplianceChecks-Msgs.psd1
- src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
This pull request adds a new module for GR11 V6
This pull request checks for a attestation file in the blob
N/A
> [New module] GR11 Validation 6 Monitoring Checklist: Use Cases

- setup/modules.json
- src/GuardRails-Localization/GR-ComplianceChecks-Msgs.psd1
- src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
This pull request adds a new module for GR13 V4
This pull request checks for a attestation file in the blob
N/A
> [New Module] GR13 Validation 4 Valid Signatures and Approvals for Break Glass Account Procedure

- src/GuardRails-Localization/fr-CA/GR-ComplianceChecks-Msgs.psd1
This pull request updates French ItemName for GR11 V6 and GR13 V4
This pull request updates French ItemName for GR11 V6 and GR13 V4
N/A
Tested
> [Update] GR11 V6 and GR13 V4: French ItemName update

- setup/tags.json
This is the pre-release step of v2.1.2
Pre-release step of updating tags.json and trigger modules update
N/A
Tested in the environment
> Pre-release v2.1.2

- setup/tags.json
This is the pre-release step of v2.1.3
Pre-release step of updating tags.json and trigger modules update
N/A
Tested in the environment
> Pre-release v2.1.3

- setup/tags.json
This is the pre-release step of v2.1.4
N/A
N/A
N/A
> Pre-release v2.1.4

- setup/tags.json
This is the pre-release step of v2.1.5
N/A
N/A
N/A
> Pre-release v2.1.5

- setup/tags.json
This is the pre-release step of v2.1.5
N/A
N/A
> Pre-release v2.1.6

- setup/tags.json
This is the pre-release step of v2.2.0
N/A
1. **Module Dependencies:** The updated implementation requires:
- `Az.ResourceGraph` version **1.1.0** or higher.
- `Az.Accounts` module updated to **4.0.2**.
- Keeping in mind new warnings show up after updating Az.Account. After some lookup, it is clear this warnings are of no concern. But this github issue mentions this in detail https://github.com/Azure/azure-powershell/issues/26155
Users with older versions of these modules must update to avoid compatibility issues.
> Pre-release v2.2.0

- .github/workflows/deploy_dev_env.yml
Temporarily turning Dev to manual for testing
> [Enhancement] - Temporarily turning Dev to manual for testing

- setup/tags.json
This is the pre-release step of v2.3.0
N/A
tenantId is now a required parameter in config.json
> Pre-release v2.3.0

- setup/tags.json
This is the pre-release step of v2.3.1
N/A
N/A
> Pre-release v2.3.1

- README.md
This Pull Request adds an upcoming release notice to the Github page.
This Pull Request adds an upcoming release notice to the Github page.
N/A
On Github main page
> [Notice] Upcoming release notice

- setup/modules.json
This Pull Request updates an existing control to recommended.
This Pull Request updates an existing control "Administrator Access Restrictions Applied - device management/trusted locations" from mandatory to recommended.
N/A
> [Update] GR3 update to recommended control

- setup/departmentList.csv
This Pull Request adds to the department list
This Pull Request adds to the department list
N/A
Csv in the feature branch
> [Update] Addition to the department list

- .github/workflows/deploy_test_env_with_tag.yml
This PR updates the deploy_test_env_with_tag.yml to manually trigger the tag selected inside the test env.
1. removed the `push:` & `branches:` to keep the workflow trigger manual and clean.
N/A
None until merged is successful.
> Add test env workflow for manual testing

- .github/workflows/deploy_test_env_with_tag.yml
This PR updates the deploy_test_env_with_tag.yml to support both manual and dev branch execution. Includes safeguards to prevent unintended runs.
- Adds dev branch to the branches: section of the deploy_test_env_with_tag.yml workflow, enabling testing workflows without impacting main.
- Removes unnecessary push triggers that could cause the pipeline to auto-execute.
- Ensures the workflow runs only on manual dispatch or pushes to main or dev, reducing CI noise and preserving intentional runs.
N/A
We need to merge prior to have any sort of testing evidence.
> Enable dev branch support in deploy_test_env_with_tag workflow

- setup/tags.json
This is the pre-release step of v2.3.2beta
N/A
N/A
> Pre-release v2.3.2beta

- setup/departmentList.csv
This Pull Request fixes the department list converting them back to string
This PR changes the file DepartmentList.csv 
N/A
Csv in the feature branch
> [Bugfix] Fix the department list

- setup/modules.json
This pull request fixes the evaluation profile for Guardrail 11 according to [GC Cloud Guardrails](https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32787)
This pull request fixes the evaluation profile for Gr11 in modules.json
N/A
> [Bugfix] GR11 V4 Fix profile evaluation list

- setup/tags.json
This is the pre-release step of v2.3.2
N/A
N/A
> [Update] Pre-release 2.3.2

- .github/workflows/auto-update-modules.yml
- .github/workflows/deploy_dev_env.yml
- .github/workflows/deploy_dev_env_with_tag.yml
- .github/workflows/deploy_test_env_with_tag.yml
- .github/workflows/release-pipeline.yml
- .github/workflows/sign-scripts-development.yml
This Pull Request updates the runners to latest
Workflow files are updates
N/A
Pipeline run completed without warning.
> Update GitHub Action Runners

- setup/IaC/guardrails.bicep
- setup/IaC/modules/automationaccount.bicep
- src/GUARDRAIL 1 PROTECT USER ACCOUNTS AND IDENTITIES/Audit/Check-AllUserMFARequired.psm1
1. Enhance MFA inquiry timing by saving the paging location where processing stopped, allowing the runbook to resume from the last processed page on the next run.
1. *Replace me*
2. *Replace me*
> Check all user mfa required repair

- setup/IaC/guardrails.bicep
- setup/IaC/modules/automationaccount.bicep
- src/GUARDRAIL 1 PROTECT USER ACCOUNTS AND IDENTITIES/Audit/Check-AllUserMFARequired.psm1
Reverts ssc-spc-ccoe-cei/azure-guardrails-solution-accelerator#539
> Revert "Check all user mfa required repair"

- setup/tags.json
This Pull Request updates the 2.3.3beta2 tag
This Pull Request updates the 2.3.3beta2 tag in tags.json
N/A
Will be tested through pipeline deployment.
> [Release Update] Pre-release Beta tag update as 2.3.3beta2

- .github/workflows/release-pipeline.yml
This Pull Request Update pipeline AzureSignIn Tool version
This Pull Request Update pipeline AzureSignIn Tool version
N/A
> [Pipeline] Update pipeline AzureSignIn Tool version
